<?php

if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_configuracoes-de-postagem',
		'title' => 'Configurações de postagem',
		'fields' => array (
			array (
				'key' => 'field_590b76114f9b8',
				'label' => 'Área de Conhecimento',
				'name' => 'area_conhecimento',
				'type' => 'select',
				'choices' => array (
					'trabalho' => 'Trabalho',
					'seguranca' => 'Seguranca e saúde no trabalho',
					'previdencia' => 'Previdência Social',
					'outros' => 'Outros',
				),
				'default_value' => '',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_590b762e4f9b9',
				'label' => 'Nível de Acesso',
				'name' => 'nivel_acesso',
				'type' => 'select',
				'choices' => array (
					'publico' => 'Público',
					'assinante' => 'Assinante',
				),
				'default_value' => '',
				'allow_null' => 0,
				'multiple' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'post',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'lex',
					'order_no' => 0,
					'group_no' => 1,
				),
			),
		),
		'options' => array (
			'position' => 'side',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_tipo-da-postagem',
		'title' => 'Tipo da postagem',
		'fields' => array (
			array (
				'key' => 'field_590b55d4c3e9e',
				'label' => 'Tipo da postagem',
				'name' => 'tipo_postagem',
				'type' => 'select',
				'required' => 1,
				'choices' => array (
					'artigo' => 'Artigo',
					'noticia' => 'Notícia',
					'materia' => 'Matéria',
				),
				'default_value' => '',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_590b56bdc3e9f',
				'label' => 'Autor',
				'name' => 'autor_artigo',
				'type' => 'text',
				'instructions' => 'Autor do artigo',
				'required' => 1,
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_590b55d4c3e9e',
							'operator' => '==',
							'value' => 'artigo',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'post',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'acf_after_title',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'excerpt',
				1 => 'custom_fields',
				2 => 'discussion',
				3 => 'comments',
				4 => 'format',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_informacoes-lex',
		'title' => 'Informações LEX',
		'fields' => array (
			array (
				'key' => 'field_590b7762f1b7b',
				'label' => 'Tipo do Ato',
				'name' => 'tipo_ato',
				'type' => 'select',
				'required' => 1,
				'choices' => array (
					'acordos_coletivos' => 'Acordos Coletivos',
					'acordos_internacionais' => 'Acordos Internacionais',
					'atos_camara_dos_deputados' => 'Atos - Câmara dos Deputados',
					'atos_conab' => 'Atos CONAB',
					'atos_declaratorios' => 'Atos Declaratórios',
					'atos_do_presidente_da_mesa_do_congresso_nacional' => 'Atos do Presidente da Mesa do Congresso Nacional',
					'atos_eletronuclear' => 'Atos Eletronuclear',
					'atos_tst' => 'Atos TST',
					'aviso' => 'Aviso',
					'circulares_bacen' => 'Circulares BACEN',
					'circulares_ggpco' => 'Circulares GGPCO',
					'circulares_cef' => 'Circulares CEF',
					'circulares_sit' => 'Circulares SIT',
					'circulares_susep' => 'Circulares SUSEP',
					'comunicados_cef' => 'Comunicados CEF',
					'consultas_publicas_cff' => 'Consultas Públicas CFF',
					'decisoes_crefito' => 'Decisões CREFITO',
					'decisoes_normativas_confea' => 'Decisões Normativas CONFEA',
					'decretos' => 'Decretos',
					'decretos_sem_numero' => 'Decretos sem Número',
					'decretos_estaduais' => 'Decretos Estaduais',
					'deliberacoes' => 'Deliberações',
					'despachos' => 'Despachos',
					'emendas_constitucionais' => 'Emendas Constitucionais',
					'instrucoes_cvm' => 'Instruções CVM',
					'instrucoes_normativas_agu' => 'Instruções Normativas AGU',
					'instrucoes_normativas_dnrc' => 'Instruções Normativas DNRC',
					'instrucoes_normativas_fnde' => 'Instruções Normativas FNDE',
					'instrucoes_normativas_inss' => 'Instruções Normativas INSS',
					'instrucoes_normativas_mpog' => 'Instruções Normativas MPOG',
					'instrucoes_normativas_mte_sit' => 'Instruções Normativas MTE & SIT',
					'instrucoes_normativas_rfb' => 'Instruções Normativas RFB',
					'instrucoes_normativas_spc' => 'Instruções Normativas SPC',
					'instrucoes_normativas_srf' => 'Instruções Normativas SRF',
					'instrucoes_normativas_srp' => 'Instruções Normativas SRP',
					'instrucoes_normativas_srt' => 'Instruções Normativas SRT',
					'instrucoes_previc' => 'Instruções Previc',
					'leis' => 'Leis',
					'leis_complementares' => 'Leis Complementares',
					'leis_estaduais' => 'Leis Estaduais',
					'leis_municipais' => 'Leis Municipais',
					'medidas_provisorias' => 'Medidas Provisórias',
					'orientacoes_normativas' => 'Orientações Normativas',
					'pareceres_agu' => 'Pareceres AGU',
					'pareceres_mps' => 'Pareceres MPS',
					'pareceres_pgfn' => 'Pareceres PGFN',
					'portarias_cjf' => 'Portarias CJF',
					'portarias_conjuntas' => 'Portarias Conjuntas',
					'portarias_drt' => 'Portarias DRT',
					'portarias_inss' => 'Portarias INSS',
					'portarias_interministeriais' => 'Portarias Interministeriais',
					'portarias_me' => 'Portarias ME',
					'portarias_mf' => 'Portarias MF',
					'portarias_mj' => 'Portarias MJ',
					'portarias_mpog' => 'Portarias MPOG',
					'portarias_mps' => 'Portarias MPS',
					'portarias_ms' => 'Portarias MS',
					'portarias_mte' => 'Portarias MTE',
					'portarias_rfb' => 'Portarias RFB',
					'portarias_sit' => 'Portarias SIT',
					'portarias_srf' => 'Portarias SRF',
					'portarias_srp' => 'Portarias SRP',
					'portarias_srt' => 'Portarias SRT',
					'portarias_ssst' => 'Portarias SSST',
					'provimento_cgjt_tst' => 'Provimento CGJT TST',
					'provimento_crps' => 'Provimento CRPS',
					'recomendacoes_cnps' => 'Recomendações CNPS',
					'recomendacoes_mte' => 'Recomendações MTE',
					'resolucoes_antaq' => 'Resoluções ANTAq',
					'resolucoes_antt' => 'Resoluções ANTT',
					'resolucoes_bacen' => 'Resoluções BACEN',
					'resolucoes_cc_fgts' => 'Resoluções CC FGTS',
					'resolucoes_cfa' => 'Resoluções CFA',
					'resolucoes_cfb' => 'Resoluções CFB',
					'resolucoes_cfbio' => 'Resoluções CFBio',
					'resolucoes_cfc' => 'Resoluções CFC',
					'resolucoes_cff' => 'Resoluções CFF',
					'resolucoes_cfm' => 'Resoluções CFM',
					'resolucoes_cfmv' => 'Resoluções CFMV',
					'resolucoes_cfn' => 'Resoluções CFN',
					'resolucoes_cfo' => 'Resoluções CFO',
					'resolucoes_cfq' => 'Resoluções CFQ',
					'resolucoes_cg_refis' => 'Resoluções CG REFIS',
					'resolucoes_cgpc' => 'Resoluções CGPC',
					'resolucoes_cjf' => 'Resoluções CJF',
					'resolucoes_cnas' => 'Resoluções CNAS',
					'resolucoes_cne_e_ceb' => 'Resoluções CNE e CEB',
					'resolucoes_cni_mte' => 'Resoluções CNI MTE',
					'resolucoes_cnj' => 'Resoluções CNJ',
					'resolucoes_cnps' => 'Resoluções CNPS',
					'resolucoes_codefat' => 'Resoluções CODEFAT',
					'resolucoes_cofecon' => 'Resoluções COFECON',
					'resolucoes_cofen' => 'Resoluções COFEN',
					'resolucoes_cofito' => 'Resoluções COFITO',
					'resolucoes_conade' => 'Resoluções CONADE',
					'resolucoes_conclan' => 'Resoluções CONCLAN',
					'resolucoes_confea' => 'Resoluções CONFEA',
					'resolucoes_confeci' => 'Resoluções CONFECI',
					'resolucoes_confef' => 'Resoluções CONFEF',
					'resolucoes_conferp' => 'Resoluções CONFERP',
					'resolucoes_conselho_superior' => 'Resoluções Conselho Superior',
					'resolucoes_conter' => 'Resoluções CONTER',
					'resolucoes_contran' => 'Resoluções CONTRAN',
					'resolucoes_crefito' => 'Resoluções CREFITO',
					'resolucoes_crps' => 'Resoluções CRPS',
					'resolucoes_csjt' => 'Resoluções CSJT',
					'resolucoes_fnde' => 'Resoluções FNDE',
					'resolucoes_inss' => 'Resoluções INSS',
					'resolucoes_mte' => 'Resoluções MTE',
					'resolucoes_omb' => 'Resoluções OMB',
					'resolucoes_pis_pasep' => 'Resoluções PIS PASEP',
					'resolucoes_senado_federal' => 'Resoluções Senado Federal',
					'resolucoes_sma_rj' => 'Resoluções SMA RJ',
					'resolucoes_srp' => 'Resoluções SRP',
					'resolucoes_susep' => 'Resoluções SUSEP',
					'resolucoes_tse' => 'Resoluções TSE',
					'resolucoes_tst' => 'Resoluções TST',
					'solucoes_de_divergencia' => 'Soluções de Divergência',
					'sumulas_stj' => 'Súmulas STJ',
					'sumulas_tst' => 'Súmulas TST',
					'sumulas_agu' => 'Súmulas AGU',
					'parecer_conjur/mte' => 'Parecer Conjur/MTE',
					'resolucoes_ibge' => 'Resoluções IBGE',
					'instrucao_normativa_inti' => 'Instrução Normativa INTI',
					'portarias_pgfn' => 'Portarias PGFN',
					'portaria_pgf' => 'Portaria PGF',
					'portaria_mma' => 'Portaria MMA',
					'legislacao_fundamental' => 'Legislação Fundamental',
					'jurisprudencia_sumulada' => 'Jurisprudência Sumulada',
					'portaria_dpu' => 'Portaria DPU',
					'solucao_de_consulta_cosit' => 'Solução de Consulta COSIT',
					'portarias_carf' => 'Portarias CARF',
					'resolucao_cgsim' => 'Resolução CGSIM',
					'resolucao_normativa_dc_ans' => 'Resolução Normativa DC ANS',
					'resolucao_cfp' => 'Resolução CFP',
					'portaria_mtps' => 'Portaria MTPS',
					'resolucao_normativa_dc/ans' => 'Resolução Normativa DC/ANS',
					'decretos_municipais' => 'Decretos Municipais',
					'resolucao_cgsn' => 'Resolução CGSN',
					'decretos_legislativos' => 'Decretos Legislativos',
					'instrucao_normativa_ans' => 'Instrução Normativa ANS',
					'recomendacoes_cff' => 'Recomendações CFF',
					'portarias_mec' => 'Portarias MEC',
					'portarias_cgu' => 'Portarias CGU',
					'resolucoes_cg_icp' => 'Resoluções CG ICP',
					'resolucoes_anac' => 'Resoluções ANAC',
					'instrucoes_normativas_mpa' => 'Instruções Normativas MPA',
					'resolucao_normativa_cnig' => 'Resolução Normativa CNIg',
					'mensagem_de_veto' => 'Mensagem de Veto',
					':' => ':',
					'portaria_agu' => 'Portaria AGU',
					'resolucoes_ans' => 'Resoluções ANS',
					'cfbm' => 'CFBM',
					'resolucoes_mj' => 'Resoluções MJ',
					'instrucao_normativa_tst' => 'Instrução Normativa TST',
					'resolucoes_cnrm' => 'Resoluções CNRM',
					'resolucao_anvisa' => 'Resolução ANVISA',
					'resolucao_normativa_aneel' => 'Resolução Normativa ANEEL',
					'ade_codac' => 'ADE CODAC',
					'resolucao_cfbm' => 'Resolução CFBM',
					'resolucao_cs_mpf' => 'Resolução CS MPF',
					'portaria_inmetro' => 'Portaria INMETRO',
					'portarias_mre' => 'PORTARIAS MRE',
				),
				'default_value' => '',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_590b7770f1b7c',
				'label' => 'Número do Ato Legal',
				'name' => 'numero_ato_legal',
				'type' => 'text',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_590b779bf1b7d',
				'label' => 'Ementa',
				'name' => 'ementa',
				'type' => 'text',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'lex',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'acf_after_title',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 1,
	));
	register_field_group(array (
		'id' => 'acf_campos-veritae',
		'title' => 'Campos Veritae',
		'fields' => array (
			array (
				'key' => 'field_590b71d8ddcad',
				'label' => 'Título Alternativo',
				'name' => 'titulo_alternativo',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_590b7299ddcaf',
				'label' => 'Arquivo',
				'name' => 'arquivo',
				'type' => 'file',
				'save_format' => 'object',
				'library' => 'uploadedTo',
			),
			array (
				'key' => 'field_590b72c4ddcb0',
				'label' => 'Fonte',
				'name' => 'fonte',
				'type' => 'text',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_590b7338ddcb1',
				'label' => 'Data Fonte',
				'name' => 'data_fonte',
				'type' => 'date_picker',
				'required' => 1,
				'date_format' => 'yymmdd',
				'display_format' => 'dd/mm/yy',
				'first_day' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'post',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'lex',
					'order_no' => 0,
					'group_no' => 1,
				),
			),
		),
		'options' => array (
			'position' => 'acf_after_title',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 2,
	));
}

