<?php

if(function_exists("register_field_group"))
{
	register_field_group(array(
		'id' => 'acf_veritae_obrigatorios',
		'title' => 'Obrigatórios',
		'fields' => array(
			array (
				'key' => 'field_590b55d4c3e9e',
				'label' => 'Tipo da postagem',
				'name' => 'tipo_postagem',
				'type' => 'select',
				'required' => 0,
				'choices' => array (
					'lex' => 'Lex',
					'noticia' => 'Notícia',
					'artigo' => 'Artigo',
					'materia' => 'Matéria',
					'informacao' => 'Informação',
					'jurisprudencia' => 'Jurisprudência',
				),
				'default_value' => '',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_590b76114f9b8',
				'label' => 'Área de Conhecimento',
				'name' => 'area_conhecimento',
				'type' => 'taxonomy',
				'required' => 0,
				'taxonomy' => 'area_conhecimento',
				'field_type' => 'checkbox',
				'allow_null' => 0,
				'load_save_terms' => 1,
				'return_format' => 'object',
				'multiple' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'post',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'acf_after_title',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	
//	register_field_group(array (
//		'id' => 'acf_configuracoes-de-postagem',
//		'title' => 'Configurações de postagem',
//		'fields' => array (
//			array (
//				'key' => 'field_590b762e4f9b9',
//				'label' => 'Nível de Acesso',
//				'name' => 'nivel_acesso',
//				'type' => 'select',
//				'choices' => array (
//					'assinante' => 'Assinante',
//					'publico' => 'Público',
//					'' => '',
//				),
//				'default_value' => 'assinante',
//				'allow_null' => 0,
//				'multiple' => 0,
//			),
//		),
//		'location' => array (
//			array (
//				array (
//					'param' => 'post_type',
//					'operator' => '==',
//					'value' => 'post',
//					'order_no' => 0,
//					'group_no' => 0,
//				),
//			),
//			array (
//				array (
//					'param' => 'post_type',
//					'operator' => '==',
//					'value' => 'post',
//					'order_no' => 0,
//					'group_no' => 1,
//				),
//			),
//		),
//		'options' => array (
//			'position' => 'side',
//			'layout' => 'default',
//			'hide_on_screen' => array (
//			),
//		),
//		'menu_order' => 1,
//	));
	register_field_group(array (
		'id' => 'acf_veritae',
		'title' => 'Veritae',
		'fields' => array (
			
			array (
				'key' => 'field_591c6b7e2a5d7',
				'label' => 'Titulo Alternativo',
				'name' => 'titulo_alternativo',
				'type' => 'text',
				'required' => 0,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_591c6c3fb6d9a',
				'label' => 'Tipo do Ato',
				'name' => 'tipo_ato',
				'type' => 'taxonomy',
				'taxonomy' => 'tipo_ato',
				'field_type' => 'select',
				'allow_null' => 0,
				'load_save_terms' => 1,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array (
				'key' => 'field_591c6c9e38bbe',
				'label' => 'Numero do Ato',
				'name' => 'numero_ato',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_591c6caf38bbf',
				'label' => 'Informações do Ato',
				'name' => 'informações_ato',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_591c6cc238bc0',
				'label' => 'Ementa',
				'name' => 'ementa',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_593054f32aeeb',
				'label' => 'Tipo do Arquivo',
				'name' => 'tipo_arquivo',
				'type' => 'radio',
				'required' => 0,
				'choices' => array (
					'local' => 'Arquivo Local',
					'remoto' => 'Arquivo Remoto',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'local',
				'layout' => 'horizontal',
			),
//			array (
//				'key' => 'field_591c6ccd38bc1',
//				'label' => 'Arquivo',
//				'name' => 'arquivo',
//				'type' => 'file',
//				'conditional_logic' => array (
//					'status' => 1,
//					'rules' => array (
//						array (
//							'field' => 'field_593054f32aeeb',
//							'operator' => '==',
//							'value' => 'local',
//						),
//					),
//					'allorany' => 'all',
//				),
//				'save_format' => 'object',
//				'library' => 'uploadedTo',
//			),
			array (
				'key' => 'field_593054cb2aeea',
				'label' => 'Arquivo URL',
				'name' => 'arquivo_url',
				'type' => 'text',
				'required' => 0,
				'instructions' => 'Insira a URL para acessar o arquivo.',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_593054f32aeeb',
							'operator' => '==',
							'value' => 'remoto',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_591c6cf338bc2',
				'label' => 'Fonte',
				'name' => 'fonte',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_591c6cfb38bc3',
				'label' => 'Data da fonte',
				'name' => 'data_fonte',
				'type' => 'date_picker',
				'date_format' => 'yy-mm-dd',
				'display_format' => 'dd/mm/yy',
				'first_day' => 0,
			),
			array (
				'key' => 'field_590b56bdc3e9f',
				'label' => 'Autor',
				'name' => 'autor_artigo',
				'type' => 'text',
				'instructions' => 'Autor do artigo',
				'required' => 0,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'post',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'acf_after_title',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'excerpt',
				1 => 'custom_fields',
				2 => 'discussion',
				3 => 'comments',
				4 => 'format',
				5 => 'categories',
				6 => 'tags',
			),
		),
		'menu_order' => 0,
	));
}

